import type { InspectableEntry } from "@/domain/workshop/types";
import { officialLsStepFlows } from "@/domain/workshop/ls-steps";

type OfficialLsLibraryEntry = Pick<
  InspectableEntry,
  | "id"
  | "title"
  | "icon"
  | "shortDescription"
  | "libraryDuration"
  | "libraryGroupSize"
  | "libraryCategoryLabel"
  | "matchmakerCategory"
  | "sourceStatus"
>;

const officialLsLibraryEntries: OfficialLsLibraryEntry[] = [
  {
    id: "124all",
    title: "1-2-4-All",
    icon: "ls-124a",
    shortDescription: "Engage Everyone Simultaneously in Generating Questions, Ideas, and Suggestions",
    libraryDuration: "12 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "15percent-solutions",
    title: "15% Solutions",
    icon: "ls-15percent-solutions",
    shortDescription: "Discover and Focus on What Each Person Has the Freedom and Resources to Do Now",
    libraryDuration: "20 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "25-10-crowd-sourcing",
    title: "25/10 Crowd Sourcing",
    icon: "ls-25-10-crowd-sourcing",
    shortDescription: "Rapidly Generate and Sift a Group's Most Powerful Actionable Ideas",
    libraryDuration: "30 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "nine-whys",
    title: "Nine Whys",
    icon: "ls-nine-whys",
    shortDescription: "Make the Purpose of Your Work Together Clear",
    libraryDuration: "20 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Analyze / Solo",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
  {
    id: "anxiety-circus",
    title: "Anxiety Circus",
    icon: "ls-anxiety-circus",
    shortDescription: "Identify the group's biggest worries, fears, and concerns",
    libraryDuration: "25-30 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "appreciative",
    title: "Appreciative Interviews",
    icon: "ls-ai",
    shortDescription: "Discovering and Building on the Root Causes of Success",
    libraryDuration: "1 hr",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Share / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "agreement-and-certainty-matrix",
    title: "Agreement & Certainty Matrix",
    icon: "ls-agreement-and-certainty-matrix",
    shortDescription: "Sort Challenges into Simple, Complicated, Complex, and Chaotic Domains",
    libraryDuration: "45 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Analyze / Solo",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
  {
    id: "celebrity-interview",
    title: "Celebrity Interview",
    icon: "ls-celebrity-interview",
    shortDescription: "Reconnect the Experience of Leaders and Experts with People Closest to the Challenge at Hand",
    libraryDuration: "35-60 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Share",
    matchmakerCategory: "share",
    sourceStatus: "official",
  },
  {
    id: "conversation-cafe",
    title: "Conversation Café",
    icon: "ls-conversation-cafe",
    shortDescription: "Engage Everyone in Making Sense of Profound Challenges",
    libraryDuration: "35-60 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Share",
    matchmakerCategory: "share",
    sourceStatus: "official",
  },
  {
    id: "critical-uncertainties",
    title: "Critical Uncertainties",
    icon: "ls-critical-uncertainties",
    shortDescription: "Develop Strategies for Operating in a Range of Plausible Yet Unpredictable Futures",
    libraryDuration: "100 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Strategize / Solo",
    matchmakerCategory: "strategize",
    sourceStatus: "official",
  },
  {
    id: "design-storyboards",
    title: "Design StoryBoards",
    icon: "ls-design-storyboards",
    shortDescription: "Define Step-by-Step Elements for Bringing Meetings to Productive Endpoints",
    libraryDuration: "25-70 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Plan / Solo",
    matchmakerCategory: "plan",
    sourceStatus: "official",
  },
  {
    id: "design-storyboards-advanced",
    title: "Design StoryBoards Advanced",
    icon: "ls-design-storyboards",
    shortDescription: "Plan productive transformation and innovation projects step by step",
    libraryDuration: "18 hrs to several days/weeks",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Plan",
    matchmakerCategory: "plan",
    sourceStatus: "official",
  },
  {
    id: "discovery-and-action-dialogue-dad",
    title: "Discovery & Action Dialogue (DAD)",
    icon: "ls-discovery-and-action-dialogue-dad",
    shortDescription: "Discover, Invent, and Unleash Local Solutions to Chronic Problems",
    libraryDuration: "25-70 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "drawing-together",
    title: "Drawing Together",
    icon: "ls-drawing-together",
    shortDescription: "Reveal Insights and Paths Forward Through Nonverbal Expression",
    libraryDuration: "40 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "ecocycle-planning",
    title: "Ecocycle Planning",
    icon: "ls-ecocycle-planning",
    shortDescription: "Analyze the Full Portfolio of Activities and Relationships to Identify Obstacles and Opportunities for Progress",
    libraryDuration: "95 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Strategize / Analyze / Solo",
    matchmakerCategory: "strategize",
    sourceStatus: "official",
  },
  {
    id: "folding-spectogram",
    title: "Folding Spectogram",
    icon: "ls-folding-spectogram",
    shortDescription: "Invite everyone to take a position on a question with controversial opinions",
    libraryDuration: "15-20 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "gallery-walk",
    title: "Gallery Walk",
    icon: "ls-gallery-walk",
    shortDescription: "Deepen shared information and ideas while moving through the room",
    libraryDuration: "6-25 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Share / Solo",
    matchmakerCategory: "share",
    sourceStatus: "official",
  },
  {
    id: "generative-relationships-star",
    title: "Generative Relationships (STAR)",
    icon: "ls-generative-relationships-star",
    shortDescription: "Reveal Relationship Patterns That Create Surprising Value or Dysfunctions",
    libraryDuration: "25 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Analyze",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
  {
    id: "grief-walking",
    title: "Grief Walking",
    icon: "ls-grief-walking",
    shortDescription: "Use social support while living through loss or profound change",
    libraryDuration: "30-60 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Help",
    matchmakerCategory: "help",
    sourceStatus: "official",
  },
  {
    id: "heard-seen-respected",
    title: "Heard, Seen, Respected",
    icon: "ls-heard-seen-respected",
    shortDescription: "Practice Deeper Listening and Empathy with Colleagues",
    libraryDuration: "35 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Help",
    matchmakerCategory: "help",
    sourceStatus: "official",
  },
  {
    id: "helping-heuristics",
    title: "Helping Heuristics",
    icon: "ls-helping-heuristics",
    shortDescription: "Practice Progressive Methods for Helping Others, Receiving Help and Asking for Help",
    libraryDuration: "15 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Help",
    matchmakerCategory: "help",
    sourceStatus: "official",
  },
  {
    id: "impromptu-networking",
    title: "Impromptu Networking",
    icon: "ls-impromptu-networking",
    shortDescription: "Rapidly Share Challenges and Expectations, Build New Connections",
    libraryDuration: "20 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Share",
    matchmakerCategory: "share",
    sourceStatus: "official",
  },
  {
    id: "improv-prototyping",
    title: "Improv Prototyping",
    icon: "ls-improv-prototyping",
    shortDescription: "Develop Effective Solutions to Chronic Challenges While Having Serious Fun",
    libraryDuration: "20 min per round",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "integrated-autonomy",
    title: "Integrated~Autonomy",
    icon: "ls-integrated-autonomy",
    shortDescription: "Move from Either-or to Robust Both-and Solutions",
    libraryDuration: "80 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Strategize / Solo",
    matchmakerCategory: "strategize",
    sourceStatus: "official",
  },
  {
    id: "mad-tea-party",
    title: "Mad Tea Party",
    icon: "ls-mad-tea-party",
    shortDescription: "Rearrange the Context for Taking Action",
    libraryDuration: "10-20 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "min-specs",
    title: "Min Specs",
    icon: "ls-min-specs",
    shortDescription: "Specify Only the Absolute \"Must dos\" and \"Must not dos\" for Achieving a Purpose",
    libraryDuration: "35-50 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Strategize / Solo",
    matchmakerCategory: "strategize",
    sourceStatus: "official",
  },
  {
    id: "network-patterning-cards",
    title: "Network Patterning Cards",
    icon: "ls-network-patterning-cards",
    shortDescription: "Identify and design more productive organizational patterns for collaboration",
    libraryDuration: "25 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "open-space-technology",
    title: "Open Space Technology",
    icon: "ls-open-space-technology",
    shortDescription: "Liberate Inherent Action and Leadership in Groups of Any Size",
    libraryDuration: "90 min to 3 days",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "panarchy",
    title: "Panarchy",
    icon: "ls-panarchy",
    shortDescription: "Understand How Embedded Systems Interact, Evolve, Spread Innovation and Transform",
    libraryDuration: "2 hrs",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Strategize / Analyze",
    matchmakerCategory: "strategize",
    sourceStatus: "official",
  },
  {
    id: "purpose-to-practice-p2p",
    title: "Purpose-To-Practice (P2P)",
    icon: "ls-purpose-to-practice-p2p",
    shortDescription: "Design the Five Essential Elements for a Resilient and Enduring Initiative",
    libraryDuration: "2 hrs",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Plan / Solo",
    matchmakerCategory: "plan",
    sourceStatus: "official",
  },
  {
    id: "shift-and-share",
    title: "Shift and Share",
    icon: "ls-shift-and-share",
    shortDescription: "Spread Good Ideas and Make Informal Connections with Innovators",
    libraryDuration: "90 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Share",
    matchmakerCategory: "share",
    sourceStatus: "official",
  },
  {
    id: "simple-ethnography",
    title: "Simple Ethnography",
    icon: "ls-simple-ethnography",
    shortDescription: "Observe and Record Actual Behaviors of Users in the Field",
    libraryDuration: "75 min to 7 hrs",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Analyze / Reveal",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
  {
    id: "social-network-webbing",
    title: "Social Network Webbing",
    icon: "ls-social-network-webbing",
    shortDescription: "Map Informal Connections and Decide How to Strengthen the Network to Achieve a Purpose",
    libraryDuration: "60 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Help / Share / Solo",
    matchmakerCategory: "help",
    sourceStatus: "official",
  },
  {
    id: "spiral-journal",
    title: "Spiral Journal",
    icon: "ls-spiral-journal",
    shortDescription: "Deepen insights and discover open questions through self-reflection",
    libraryDuration: "10-20 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Analyze / Solo",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
  {
    id: "talking-with-pixies",
    title: "Talking with Pixies",
    icon: "ls-talking-with-pixies",
    shortDescription: "Identify and break through beliefs and assumptions that constrain your action",
    libraryDuration: "30 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Help / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "tiny-demons",
    title: "Tiny Demons",
    icon: "ls-tiny-demons",
    shortDescription: "Explore personal inner blockers and convert them into insight",
    libraryDuration: "12-20 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "triz",
    title: "TRIZ",
    icon: "ls-triz",
    shortDescription: "Stop Counterproductive Activities and Behaviors to Make Space for Innovation",
    libraryDuration: "35 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "troika-consulting",
    title: "Troika Consulting",
    icon: "ls-troika-consulting",
    shortDescription: "Get Practical and Imaginative Help from Colleagues Immediately",
    libraryDuration: "30 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal / Help",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "user-experience-fishbowl",
    title: "User Experience Fishbowl",
    icon: "ls-user-experience-fishbowl",
    shortDescription: "Share Know-How Gained from Experience with a Larger Community",
    libraryDuration: "35-70 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Share",
    matchmakerCategory: "share",
    sourceStatus: "official",
  },
  {
    id: "winfy",
    title: "What I Need From You",
    icon: "ls-winfy",
    shortDescription: "Surface Essential Needs Across Functions and Accept or Reject Requests for Support",
    libraryDuration: "55-70 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Help",
    matchmakerCategory: "help",
    sourceStatus: "official",
  },
  {
    id: "what-so-what-now-what",
    title: "What, So What, Now What?",
    icon: "ls-what-so-what-now-what",
    shortDescription: "Together, Look Back on Progress to Date and Decide What Adjustments Are Needed",
    libraryDuration: "45 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Analyze / Solo",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
  {
    id: "wicked-questions",
    title: "Wicked Questions",
    icon: "ls-wicked-questions",
    shortDescription: "Articulate the Paradoxical Challenges That a Group Must Confront to Succeed",
    libraryDuration: "25 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Reveal / Solo",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "wise-crowds",
    title: "Wise Crowds",
    icon: "ls-wise-crowds",
    shortDescription: "Tap the Wisdom of the Whole Group in Rapid Cycles",
    libraryDuration: "15 min per person",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal / Help",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "wise-crowds-fur-grosse-gruppen",
    title: "Wise Crowds for Large Groups",
    icon: "ls-wise-crowds",
    shortDescription: "Use the knowledge of individual experts and the whole group",
    libraryDuration: "60 min",
    libraryGroupSize: "Group",
    libraryCategoryLabel: "Reveal / Help",
    matchmakerCategory: "reveal",
    sourceStatus: "official",
  },
  {
    id: "xxn-writing",
    title: "XxN-Writing",
    icon: "ls-xxn-writing",
    shortDescription: "Sharpen and focus thinking through a sequence of questions or statements",
    libraryDuration: "10-25 min",
    libraryGroupSize: "Solo / group",
    libraryCategoryLabel: "Analyze / Solo",
    matchmakerCategory: "analyze",
    sourceStatus: "official",
  },
];

export const officialLsEntries = Object.fromEntries(
  officialLsLibraryEntries.map((entry) => {
    const fitCuesByCategory: Record<NonNullable<InspectableEntry["matchmakerCategory"]>, [string, string, string]> = {
      share: ["share knowledge", "connect people", "spread ideas"],
      reveal: ["surface patterns", "include voices", "discover options"],
      analyze: ["make sense", "debrief", "clarify patterns"],
      strategize: ["shape strategy", "explore futures", "set direction"],
      help: ["give help", "ask clearly", "build support"],
      plan: ["prepare work", "design flow", "align action"],
    };
    const fitCues = fitCuesByCategory[entry.matchmakerCategory ?? "reveal"];

    return [
      entry.id,
      {
        ...entry,
        badge: "Liberating Structure",
        kind: "ls",
        typeLabel: entry.libraryCategoryLabel ?? "Liberating Structure",
        description: entry.shortDescription,
        review: "Use this official Liberating Structure when its purpose, timing, and participation pattern fit the section goal.",
        notes: "Adapt the invitation and timebox to the workshop context while preserving the structure's core pattern.",
        output: "A facilitation output aligned with the structure's official purpose.",
        fitCues,
        steps: officialLsStepFlows[entry.id],
        suggestions: [
          "Check whether the stated purpose matches the section goal.",
          "Keep the invitation short enough that participants know exactly what to do.",
        ],
        reviewSummary: {
          label: "Official LS",
          score: "Library",
          tone: "info",
        },
        libraryMeta: `${entry.libraryDuration} • ${entry.libraryCategoryLabel} • Official`,
        libraryDescription: entry.shortDescription,
      } satisfies InspectableEntry,
    ];
  }),
) as Record<string, InspectableEntry>;
